// 配布物に含まれる第三者ソフトウェアの一覧（THIRD-PARTY-NOTICES）を生成する。
// AuraCapはプロプライエタリ配布なので、同梱するOSSの表示義務を満たすために必要。
// Rust側は `cargo metadata`、npm側は package.json の dependencies から実際に
// バンドルへ入るものだけを辿る（devDependenciesは配布物に含まれないため除外）。
//
// Generates THIRD-PARTY-NOTICES for the components shipped inside AuraCap. Required because
// AuraCap is distributed under a proprietary license and must carry the bundled OSS notices.
// Rust comes from `cargo metadata`; npm walks package.json dependencies only (devDependencies
// never reach the bundle).
//
// 使い方 / Usage: node scripts/gen_third_party_notices.mjs

import { execFileSync } from "node:child_process";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");

// ---- Rust ----

function rustPackages() {
  const raw = execFileSync(
    "cargo",
    ["metadata", "--format-version", "1", "--all-features"],
    { cwd: path.join(root, "src-tauri"), encoding: "utf8", maxBuffer: 128 * 1024 * 1024 },
  );
  const meta = JSON.parse(raw);
  return meta.packages
    .filter((p) => p.name !== "auracap")
    .map((p) => ({ name: p.name, version: p.version, license: p.license ?? "(unspecified)" }))
    .sort((a, b) => a.name.localeCompare(b.name) || a.version.localeCompare(b.version));
}

// ---- npm ----

/// package.json の dependencies を再帰的に辿る。node_modulesはフラットに置かれるので
/// 名前解決はトップレベルを見れば足りる（ネストされている場合のみ潜る）。
/// Walk dependencies recursively. node_modules is flat, so top-level lookup suffices,
/// with a fallback into the nested copy when one exists.
function readPkg(dir) {
  try {
    return JSON.parse(fs.readFileSync(path.join(dir, "package.json"), "utf8"));
  } catch {
    return null;
  }
}

function resolvePkgDir(name, fromDir) {
  const nested = path.join(fromDir, "node_modules", name);
  if (fs.existsSync(path.join(nested, "package.json"))) return nested;
  const top = path.join(root, "node_modules", name);
  return fs.existsSync(path.join(top, "package.json")) ? top : null;
}

function npmPackages() {
  const found = new Map();
  const rootPkg = readPkg(root);
  const queue = Object.keys(rootPkg?.dependencies ?? {}).map((n) => [n, root]);
  while (queue.length) {
    const [name, from] = queue.shift();
    const dir = resolvePkgDir(name, from);
    if (!dir) continue;
    const pkg = readPkg(dir);
    if (!pkg?.version) continue;
    const key = `${pkg.name}@${pkg.version}`;
    if (found.has(key)) continue;
    const license =
      pkg.license ?? (pkg.licenses ? pkg.licenses.map((l) => l.type ?? l).join(" OR ") : "(unspecified)");
    found.set(key, { name: pkg.name, version: pkg.version, license });
    for (const dep of Object.keys(pkg.dependencies ?? {})) queue.push([dep, dir]);
  }
  return [...found.values()].sort(
    (a, b) => a.name.localeCompare(b.name) || a.version.localeCompare(b.version),
  );
}

// ---- 出力 / Output ----

function summarize(pkgs) {
  const by = new Map();
  for (const p of pkgs) by.set(p.license, (by.get(p.license) ?? 0) + 1);
  return [...by.entries()].sort((a, b) => b[1] - a[1]);
}

function table(pkgs) {
  return pkgs.map((p) => `| ${p.name} | ${p.version} | ${p.license} |`).join("\n");
}

const rust = rustPackages();
const npm = npmPackages();

const out = `# THIRD-PARTY NOTICES

AuraCap には以下のオープンソースコンポーネントが含まれます。各コンポーネントは
それぞれの提供者が定めるライセンス条件のもとで利用しており、当該部分については
本ソフトウェアの [LICENSE](./LICENSE) ではなく各ライセンスが適用されます。

AuraCap includes the open-source components listed below. Each is used under the terms set by
its own authors; for those components their license governs, not AuraCap's [LICENSE](./LICENSE).

このファイルは \`node scripts/gen_third_party_notices.mjs\` で生成しています。
依存を追加・更新したら再生成してください。
Generated by \`node scripts/gen_third_party_notices.mjs\`; regenerate whenever dependencies change.

生成日時 / Generated: ${new Date().toISOString().slice(0, 10)}

## 注意が必要なライセンス / Licenses needing attention

- **MPL-2.0**: ファイル単位のコピーレフト。同梱しているものは未改変のため、
  ソース入手先（crates.io / npm）を示せば足ります。改変した場合は当該ファイルの
  ソース公開が必要です。
  File-level copyleft. The bundled copies are unmodified, so pointing at the upstream source
  (crates.io / npm) is sufficient; modifying them would require publishing those files.
- **Apache-2.0**: ライセンス全文と NOTICE ファイルの同梱が必要です。
  Requires shipping the full license text and any NOTICE file.
- **Unicode-3.0 / BSD / ISC / BSL-1.0 / CC-BY-4.0**: 著作権表示とライセンス条文の
  表示が必要です。
  Require reproducing the copyright notice and license terms.

各ライセンスの全文は配布パッケージの \`licenses/\` に同梱します。
Full license texts are shipped in \`licenses/\` alongside the distributed package.

## Rust クレート / Rust crates (${rust.length})

ライセンス別の内訳 / Breakdown by license:

${summarize(rust).map(([l, n]) => `- ${l}: ${n}`).join("\n")}

| Package | Version | License |
|---|---|---|
${table(rust)}

## npm パッケージ / npm packages (${npm.length})

配布物に含まれる依存のみ（devDependenciesは対象外）。
Only dependencies that reach the bundle; devDependencies are excluded.

ライセンス別の内訳 / Breakdown by license:

${summarize(npm).map(([l, n]) => `- ${l}: ${n}`).join("\n")}

| Package | Version | License |
|---|---|---|
${table(npm)}
`;

fs.writeFileSync(path.join(root, "THIRD-PARTY-NOTICES.md"), out);
console.log(`THIRD-PARTY-NOTICES.md: ${rust.length} crates, ${npm.length} npm packages`);
